# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fzkPTmais3iblptM5n0oNluQRUpHlKiO
"""

!pip install -q tensorflow matplotlib pillow

print("Librerías instaladas")

"""DESCARGAR DATASET PLANTVILLAGE"""

!wget -q https://github.com/spMohanty/PlantVillage-Dataset/archive/refs/heads/master.zip
!unzip -q master.zip
!mv PlantVillage-Dataset-master plantvillage

print(" Dataset descargado")

"""PREPARAR RUTAS DE MAÍZ"""

import os
import shutil

base_dir = "/content/data"
os.makedirs(base_dir, exist_ok=True)

plantvillage_dir = "/content/plantvillage/raw/color"

healthy_dir = os.path.join(plantvillage_dir, "Corn_(maize)___healthy")

diseased_dirs = [
    os.path.join(plantvillage_dir, "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot"),
    os.path.join(plantvillage_dir, "Corn_(maize)___Common_rust_"),
    os.path.join(plantvillage_dir, "Corn_(maize)___Northern_Leaf_Blight")
]

"""CARGAR IMÁGENES RGB"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np

IMG_SIZE = 128

def load_images_from_folder(folder_list):
    images = []
    for folder in folder_list:
        for filename in os.listdir(folder):
            if filename.lower().endswith(('.jpg', '.png', '.jpeg')):
                path = os.path.join(folder, filename)
                img = load_img(path, target_size=(IMG_SIZE, IMG_SIZE))
                img = img_to_array(img)
                images.append(img)
    return np.array(images)

print(" Cargando imágenes.")

healthy_images = load_images_from_folder([healthy_dir])
diseased_images = load_images_from_folder(diseased_dirs)

print("Sanas:", healthy_images.shape)
print("Enfermas:", diseased_images.shape)

"""NORMALIZAR (0-1) PARA RGB"""

healthy_images = healthy_images.astype("float32") / 255.
diseased_images = diseased_images.astype("float32") / 255.

# Unimos todo para autoencoder (aprende reconstrucción)
x_data = np.concatenate([healthy_images, diseased_images], axis=0)

print("Dataset total:", x_data.shape)

"""AUTOENCODER CONVOLUCIONAL"""

from tensorflow import keras
from tensorflow.keras import layers

input_img = keras.Input(shape=(128, 128, 3))

# Encoder
x = layers.Conv2D(32, (3,3), activation='relu', padding='same')(input_img)
x = layers.MaxPooling2D((2,2), padding='same')(x)

x = layers.Conv2D(64, (3,3), activation='relu', padding='same')(x)
x = layers.MaxPooling2D((2,2), padding='same')(x)

x = layers.Conv2D(128, (3,3), activation='relu', padding='same')(x)
encoded = layers.MaxPooling2D((2,2), padding='same')(x)

# Decoder
x = layers.Conv2D(128, (3,3), activation='relu', padding='same')(encoded)
x = layers.UpSampling2D((2,2))(x)

x = layers.Conv2D(64, (3,3), activation='relu', padding='same')(x)
x = layers.UpSampling2D((2,2))(x)

x = layers.Conv2D(32, (3,3), activation='relu', padding='same')(x)
x = layers.UpSampling2D((2,2))(x)

decoded = layers.Conv2D(3, (3,3), activation='sigmoid', padding='same')(x)

autoencoder = keras.Model(input_img, decoded)
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')

autoencoder.summary()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
from tensorflow.keras.callbacks import TensorBoard

log_dir = "/content/logs"

history = autoencoder.fit(
    x_data, x_data,
    epochs=20,
    batch_size=32,
    shuffle=True,
    validation_split=0.2,
    callbacks=[TensorBoard(log_dir=log_dir)]
)

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir /content/logs

"""RECONSTRUCCIONES"""

import matplotlib.pyplot as plt

decoded_imgs = autoencoder.predict(x_data[:10])

n = 5
plt.figure(figsize=(15,6))

for i in range(n):
    # Original
    ax = plt.subplot(2, n, i+1)
    plt.imshow(x_data[i])
    plt.axis("off")

    # Reconstrucción
    ax = plt.subplot(2, n, i+n+1)
    plt.imshow(decoded_imgs[i])
    plt.axis("off")

plt.show()